ARG GITHUB_SHA
FROM mormahr/pdf-service:${GITHUB_SHA}

RUN apt-get update \
    && apt-get install -y \
        poppler-utils \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -e '.[dev]'

ENTRYPOINT [ "python", "toolbox.py" ]
