version: "3"
services:
  test:
    build: .
    volumes:
      - "./tests:/usr/src/app/tests"
      - "./test-data:/usr/src/app/test-data"
      - "./src:/usr/src/app/src"
      - "./.pytest_cache:/usr/src/app/.pytest_cache"
    command: python -m pytest
  test-watch:
    build: .
    volumes:
      - "./tests:/usr/src/app/tests"
      - "./test-data:/usr/src/app/test-data"
      - "./src:/usr/src/app/src"
      - "./.pytest_cache:/usr/src/app/.pytest_cache"
    command: pytest-watch -p
