version: "3"
services:
  test:
    build: .
    volumes:
      - "./tests:/usr/src/app/tests"
      - "./test-data:/usr/src/app/test-data"
      - "./src:/usr/src/app/src"
      - "./coverage:/usr/src/app/coverage"
      - "./.pytest_cache:/usr/src/app/.pytest_cache"
    command: |
      python -m pytest
        --cov=pdf_service
        --cov-report term
        --cov-report html:coverage/cov_html
        --cov-report xml:coverage/cov.xml
        --cov-report annotate:coverage/cov_annotate
  test-watch:
    build: .
    volumes:
      - "./tests:/usr/src/app/tests"
      - "./test-data:/usr/src/app/test-data"
      - "./src:/usr/src/app/src"
      - "./.pytest_cache:/usr/src/app/.pytest_cache"
    command: pytest-watch -p
  update-test-data:
    build: .
    volumes:
      - "./tests:/usr/src/app/tests"
      - "./test-data:/usr/src/app/test-data"
      - "./src:/usr/src/app/src"
    command: python pdf_service/toolbox.py update
