version: "3.8"
services:
  pdf:
    image: "mormahr/pdf-service:${TAG}"
    platform: ${PLATFORM}

  test:
    image: "mormahr/pdf-service:${TAG}-e2e"
    links:
      - "pdf:pdf"
    volumes:
      - "./diffs:/root/diffs"
