name: Release
on:
  push:
    tags:
      - 'v**'

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: mormahr/pdf-service
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=main
            type=sha,format=long

      - name: Install jq
        run: sudo apt-get install jq

      - name: Tag
        env:
          INPUT_TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          echo "$INPUT_TAGS" | while read -r TAG
          do
            echo "tagging $TAG"
            MANIFEST_LIST=$( \
              docker manifest inspect mormahr/pdf-service:sha-${{ github.sha }} | \
              jq -rc '.manifests[].digest' | \
              sed -e 's/^/mormahr\/pdf-service@/' | \
              tr '\n' ' ' \
            )
            docker manifest create "$TAG" $MANIFEST_LIST
            docker manifest push "$TAG"
          done
